name: terraform-validate
on:
  push:
    branches-ignore:
      - "main"

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5
      - name: Run Terraform Validate
        run: |
          terraform -chdir=test init
          terraform -chdir=test validate
